/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.musicrizz.gameoflife.vista;

import it.musicrizz.gameoflife.Bundle;
import it.musicrizz.gameoflife.Costanti;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.JLabel;

/**
 *
 * @author Grandinetti Giovanni <musicrizz@hotmail.it>
 */
public class PannelloIniziale extends javax.swing.JPanel {
    
    private JLabel label;
    private Image img;
    /**
     * Creates new form PannelloIniziale
     */
    public PannelloIniziale() {
        initComponents();
        setBackground(Color.WHITE);
        label = new JLabel();
        try{
            img = ImageIO.read(PannelloIniziale.class.getResource(Costanti.ICONA_PANNELLO_INIT));
        }catch(Exception e)   {
            label.setText(Bundle.getString(Costanti.ERROR_ICONA_PANNELLO_INIZIALE, e.toString()));
            this.add(label);
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(img == null) return;
        g.drawImage(img, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
