/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.musicrizz.gameoflife.vista;

import it.unibas.ping.binding.osservatori.OsservatoreLista;
import it.unibas.ping.framework.Controllo;
import it.musicrizz.gameoflife.Costanti;
import it.musicrizz.gameoflife.chat.MessaggiChat;
import it.musicrizz.gameoflife.controllo.AzioneCancellaMessaggi;
import it.musicrizz.gameoflife.controllo.AzioneSendMessage;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author Grandinetti Giovanni <musicrizz@hotmail.it>
 */
public class PannelloChat extends javax.swing.JPanel {
    
    private JList listaMessaggi;
    private Controllo controllo;
    /**
     * Creates new form PannelloChat
     */
    public PannelloChat(Controllo control) {
        controllo = control;
        initComponents();
        initListaMessaggi();
        initButton();
    }
    
        @SuppressWarnings("unchecked")
    private void initListaMessaggi()   {
        listaMessaggi = new JList();
        listaMessaggi.setDragEnabled(false);
        listaMessaggi.setCellRenderer(new CellRenderChat());
        new OsservatoreLista(listaMessaggi, Costanti.MESSAGGI_CHAT, MessaggiChat.class, Costanti.MESSAGGI_CHAT_LISTA);
        jScrollPane1.setViewportView(listaMessaggi);
    }
    
    private void initButton()   {
        jButtonSend.setAction(controllo.getAzioneSwing(AzioneSendMessage.class.getName()));
        
        jButtonCancellaConversazione.setAction(controllo.getAzioneSwing(AzioneCancellaMessaggi.class.getName()));
    }
    
    public String getMessage()   {
        return jTextArea1.getText();
    }
    
    public void pulisciTextArea()   {
        jTextArea1.setText("");
    }
    
    public void setTextButtonSend(String text)   {
         jButtonSend.setText(text);
    }
    
    public void setTextButtonCancConv(String text)   {
        jButtonCancellaConversazione.setText(text);
    }
    
    public void setTitleBorder(String title)   {
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
                                                                    title, 
                                                                    javax.swing.border.TitledBorder.CENTER, 
                                                                    javax.swing.border.TitledBorder.TOP, 
                                                                    null, new java.awt.Color(0, 0, 255)));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancellaConversazione = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conversazione", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        jButtonCancellaConversazione.setText("Cancella Conversazione");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButtonSend.setText("Invia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButtonCancellaConversazione)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSend)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonCancellaConversazione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSend)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancellaConversazione;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
